apiVersion: v1
kind: ConfigMap
metadata:
  name: nephos-config
  namespace: nephos
data:
  ENVIRONMENT: "dev"
  AUTH_SERVICE_URL: "http://auth-service.nephos.svc.cluster.local:8000/api/v1"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.nephos.svc.cluster.local:5672/"
